spring:
  datasource:
    url: jdbc:postgresql://ep-flat-cake-ai36cxqu-pooler.c-4.us-east-1.aws.neon.tech/payment_system?sslmode=require
    username: neondb_owner
    password: npg_ktLraj2Dp4mU
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
      file-size-threshold: 2KB
#      max-file-count: 10

server:
  tomcat:
    max-swallow-size: -1
    max-part-count: 20



